import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import { getServerSession } from "next-auth";
import Link from "next/link";
import Logout from "@/components/logout";
import { Toaster } from "@/components/ui/toaster"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <nav>
            {!!session &&
            (  <Logout /> )
            }
            {!session &&
            (  <Link href="/login">
                Login
              </Link>
              )
            }
          </nav>
          {children}

        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
